on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.yarn
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: yarn-

      - name: Install modules
        run: yarn install

      - name: ESLint
        run: ./node_modules/.bin/eslint '**/*.ts' --fix

      - name: Prettier
        run: ./node_modules/.bin/prettier --check .
